### ISSUE TITLE
Todo list for first release

### ISSUE THREAD

**Issue by yblein** [yblein/tavor-isa#3]
- [x] setable RNG seed
- [x] rename "arrays" to "variables"
- [x] develop a new strategy performing token coverage in Tavor
- [x] set up an interrupt handler for tests that trap
- [x] blog post

**Comment by yblein** [comment]
[Release article](doc/2015-07-25_first-release.md)
